export const questions = [
  { id: 1, text: "If confronted by a time-traveling version of yourself, what is your first move?", options: ["Fight to the death", "Ask for lottery numbers", "Compliment their outfit", "Run away screaming"] },
  { id: 2, text: "Which of these is a valid reason to cry in a supermarket?", options: ["They are out of the good cheese", "The fluorescent lights are too loud", "A potato looked at me funny", "I forgot why I came here"] },
  { id: 3, text: "Choose a weapon for the impending goose uprising:", options: ["A slightly damp towel", "A megaphone that only plays jazz", "Pocket sand", "Diplomacy (it won't work)"] },
  { id: 4, text: "What is your designated role in a post-apocalyptic society?", options: ["Warlord", "The guy who dies first", "Keeper of the sacred Wi-Fi password", "Professional rock stacker"] },
  { id: 5, text: "How many toddlers could you reasonably fight in a zero-gravity environment?", options: ["0-5", "6-15", "16-30", "Bring on the horde"] },
  { id: 6, text: "If you were a kitchen appliance, what would be your fatal flaw?", options: ["I burn everything", "I make threatening noises at 3 AM", "I only work when complimented", "I am a single-use avocado slicer"] },
  { id: 7, text: "What is the most acceptable thing to do in an elevator?", options: ["Face the back wall", "Hum the Jeopardy theme", "Offer everyone a single bean", "Stand perfectly still and don't blink"] },
  { id: 8, text: "You find a mysterious button that says 'DO NOT PUSH'. What do you do?", options: ["Push it immediately", "Push it with a stick", "Stare at it aggressively", "Call my mom"] },
  { id: 9, text: "What is your spirit cryptid?", options: ["Mothman (anxious, likes lamps)", "Bigfoot (blurry, avoids people)", "Loch Ness Monster (needs about tree fiddy)", "Chupacabra (just hungry)"] },
  { id: 10, text: "Which minor inconvenience would you wish upon your worst enemy?", options: ["Warm pillows on both sides", "USB never plugs in on the first try", "Slightly damp socks forever", "Every chair squeaks loudly"] },
  { id: 11, text: "What is the correct response to someone waving at the person behind you?", options: ["Wave back anyway", "Flee the country", "Pretend to stretch", "Stare into the void"] },
  { id: 12, text: "If your life was a movie, what genre would it be?", options: ["Tragicomedy", "Psychological Horror", "A very boring documentary", "Surrealist French Cinema"] },
  { id: 13, text: "What is your preferred method of escaping an awkward conversation?", options: ["Smoke bomb", "Fake a phone call", "Slowly back away into a bush", "Yell 'LOOK, A DISTRACTION!'"] },
  { id: 14, text: "Which of these smells brings you the most comfort?", options: ["Gasoline", "Old books", "Impending doom", "Freshly baked bread"] },
  { id: 15, text: "What is your stance on the existence of birds?", options: ["They are government drones", "They are dinosaurs in disguise", "They are okay, I guess", "I am a bird"] },
  { id: 16, text: "If you had to eat one thing for the rest of your life, what would it be?", options: ["Pizza", "Photosynthesis", "The rich", "Just plain mayonnaise"] },
  { id: 17, text: "What is your ideal weekend activity?", options: ["Sleeping for 14 hours", "Staring at a wall", "Arguing with strangers online", "Summoning ancient deities"] },
  { id: 18, text: "How do you handle minor criticism?", options: ["Constructively", "With immediate tears", "By plotting revenge", "I reject your reality"] },
  { id: 19, text: "What is the most terrifying shape?", options: ["A non-Euclidean hypercube", "A slightly asymmetrical circle", "The IRS logo", "A triangle with attitude"] },
  { id: 20, text: "If you could instantly master one useless skill, what would it be?", options: ["Juggling invisible balls", "Speaking fluent dolphin", "Perfectly folding fitted sheets", "Guessing people's Wi-Fi passwords"] },
  { id: 21, text: "What is your primary defense mechanism?", options: ["Sarcasm", "Playing dead", "Incoherent screaming", "Aggressive finger guns"] },
  { id: 22, text: "Which of these is a completely rational fear?", options: ["Ducks watching you", "Gravity turning off", "Roomba gaining sentience", "Running out of cheese"] },
  { id: 23, text: "What is the best way to assert dominance?", options: ["T-pose", "Maintain unbroken eye contact", "Eat a kiwi with the skin on", "Speak only in riddles"] },
  { id: 24, text: "If you were a ghost, who would you haunt?", options: ["My ex", "People who chew loudly", "The CEO of a major corporation", "I'd just haunt a nice bakery"] },
  { id: 25, text: "What is your preferred mode of transportation?", options: ["Teleportation", "A majestic steed", "Rolling down a hill", "Public transit, but it's always on time"] },
  { id: 26, text: "Which of these is the most acceptable pizza topping?", options: ["Pineapple", "Anchovies", "Existential dread", "More pizza"] },
  { id: 27, text: "What is your strategy for surviving a zombie apocalypse?", options: ["Befriend the zombies", "Hide in a Costco", "I would simply perish", "Become the zombie king"] },
  { id: 28, text: "If you had a warning label, what would it say?", options: ["Contents under pressure", "May contain nuts", "Do not perceive", "Requires frequent naps"] },
  { id: 29, text: "What is the most suspicious vegetable?", options: ["Eggplant", "Celery (it's just crunchy water)", "Brussels sprouts", "A perfectly spherical potato"] },
  { id: 30, text: "How do you react when someone sings 'Happy Birthday' to you?", options: ["Smile awkwardly", "Conduct them like a maestro", "Stare at the cake", "Dissolve into dust"] },
  { id: 31, text: "What is your favorite conspiracy theory?", options: ["The moon is a hologram", "Finland doesn't exist", "Pigeons are spies", "I am the only real person"] },
  { id: 32, text: "If you could communicate with one inanimate object, what would it be?", options: ["My bed", "The fridge", "My Wi-Fi router", "A very judgmental lamp"] },
  { id: 33, text: "What is the worst superpower to have?", options: ["Invisibility, but only when no one is looking", "The ability to fly, but only 2 inches off the ground", "Super strength, but only against pillows", "Mind reading, but only for squirrels"] },
  { id: 34, text: "How do you prepare for a difficult task?", options: ["Procrastinate until the last minute", "Make a detailed plan and ignore it", "Cry a little bit", "Drink 4 cups of coffee and hope for the best"] },
  { id: 35, text: "What is your signature dance move?", options: ["The awkward shuffle", "The sprinkler", "Standing perfectly still", "Flailing wildly"] },
  { id: 36, text: "If you were a color, what would you be?", options: ["Vantablack", "Neon beige", "A color that doesn't exist yet", "Plaid"] },
  { id: 37, text: "What is the most overrated human experience?", options: ["Going outside", "Small talk", "Wearing pants", "Being awake"] },
  { id: 38, text: "How do you handle a spider in your room?", options: ["Burn the house down", "Capture and release", "Name it and accept it as a roommate", "Scream until someone else deals with it"] },
  { id: 39, text: "What is your ideal pet?", options: ["A dog", "A cat", "A miniature dragon", "A rock with googly eyes"] },
  { id: 40, text: "If you could replace your hands with anything, what would you choose?", options: ["Spatulas", "Crab claws", "Laser pointers", "I like my hands, thanks"] },
  { id: 41, text: "What is the most confusing emotion?", options: ["Nostalgia for a time you never lived in", "Being angry but also hungry (hangry)", "The urge to squeeze something cute", "Feeling bad for an inanimate object"] },
  { id: 42, text: "How do you prefer your water?", options: ["Ice cold", "Room temperature", "Sparkling", "In the form of coffee"] },
  { id: 43, text: "What is your strategy for winning a staring contest?", options: ["Don't blink", "Make a weird face", "Think about sad things", "I always lose"] },
  { id: 44, text: "If you were a piece of furniture, what would you be?", options: ["A comfortable armchair", "A wobbly table", "A very judgmental mirror", "A bookshelf full of unread books"] },
  { id: 45, text: "What is the most acceptable time to eat breakfast food?", options: ["Morning", "Midnight", "Anytime", "Never"] },
  { id: 46, text: "How do you react to a compliment?", options: ["Deflect immediately", "Accept it gracefully", "Assume it's a trap", "Compliment them back aggressively"] },
  { id: 47, text: "What is your favorite way to waste time?", options: ["Scrolling endlessly", "Staring into space", "Overthinking past conversations", "Organizing things that don't need organizing"] },
  { id: 48, text: "If you could only use one emoji for the rest of your life, what would it be?", options: ["😂", "💀", "🙃", "🥔"] },
  { id: 49, text: "What is the most chaotic neutral action?", options: ["Eating cereal with water", "Putting the toilet paper roll on backwards", "Saying 'you too' when the waiter says 'enjoy your meal'", "Walking slowly in a busy hallway"] },
  { id: 50, text: "How do you know when you've officially become an adult?", options: ["You get excited about a new sponge", "You have a favorite grocery store", "You make noises when you sit down", "It's a myth, no one is an adult"] },
  { id: 51, text: "What is the true purpose of the appendix?", options: ["To randomly explode", "Storing backup snacks", "It's a government tracking device", "Nobody knows"] },
  { id: 52, text: "If you were a font, which one would you be?", options: ["Comic Sans (chaotic evil)", "Times New Roman (boring but reliable)", "Papyrus (you think you're fancy)", "Wingdings (incomprehensible)"] }
];

export const results = [
  "You are 63% potato 🥔",
  "You would survive exactly 2 days in space before pressing the wrong button.",
  "Your spirit animal is a Roomba stuck in a corner.",
  "You give off strong 'unsupervised toddler in a grocery store' energy.",
  "You are the human equivalent of a typo in a very serious email.",
  "If you were a ghost, you would just slightly move people's keys.",
  "You have the survival instincts of a lemming on a caffeine crash.",
  "Your aura is the color of a dial-up modem sound.",
  "You are legally classified as a minor inconvenience.",
  "You would absolutely try to pet a wild bear if it looked sad.",
  "You are 90% anxiety and 10% caffeine.",
  "Your superpower is making situations exactly 12% more awkward.",
  "You are the reason aliens lock their doors when they fly past Earth.",
  "If left alone in a forest, you would accidentally become a cryptid.",
  "You are the embodiment of the 'this is fine' dog.",
  "Your brain operates on Internet Explorer 6.",
  "You have the chaotic energy of a raccoon in a dumpster.",
  "You are a background character in someone else's fever dream.",
  "You would fail a Turing test.",
  "Your ideal habitat is a cozy blanket fort with Wi-Fi.",
  "You are 100% likely to apologize to an inanimate object after bumping into it.",
  "You possess the raw, untamed power of a slightly damp paper towel.",
  "You are the human version of a 404 Error.",
  "If you were a cryptid, your blurry photo would just be you eating a sandwich.",
  "You are a sentient pile of laundry avoiding being folded.",
  "Your destiny is to become a mildly famous local eccentric.",
  "You are the patron saint of overthinking text messages.",
  "You have the emotional range of a teaspoon, but a very nice teaspoon.",
  "You are 40% water, 60% existential dread.",
  "You would definitely push the big red button just to see what happens."
];
